---
name: statix
description: Lints and suggestions for the Nix programming language.
homepage: https://github.com/oppiliappan/statix
licenses:
  - MIT
languages:
  - Nix
categories:
  - LSP

source:
  id: pkg:cargo/statix@0.5.8?features=json?repository_url=https://github.com/oppiliappan/statix

bin:
  statix: cargo:statix
